In [3]:
import os
import json
import requests
import pandas as pd
import calendar, datetime
from bs4 import BeautifulSoup
from matplotlib import pyplot as plt

%matplotlib inline 

def dt(u): return datetime.datetime.utcfromtimestamp(u)
def ut(d): return calendar.timegm(d.timetuple())

url = "https://api.coinmarketcap.com/v1/ticker/"
response = requests.get(url,verify=False)
soup = BeautifulSoup(response.content, "html.parser")
dic = json.loads(soup.prettify())
 
# create an empty DataFrame
df = pd.DataFrame(columns=["Ticker", "MarketCap"])
 
for i in range(len(dic)):
    df.loc[len(df)] = [dic[i]['symbol'], dic[i]['market_cap_usd']]
 
df.sort_values(by=['MarketCap'])
# apply conversion to numeric as 'df' contains lots of 'None' string as values
df.MarketCap = pd.to_numeric(df.MarketCap)

/home/cesar/Desktop/GraphsDynamics/graphs/local/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

In [8]:
os.listdir("../../data")

['temporalmotif',
 'bigclam',
 'graph',
 'PoissonMeasure.pdf',
 'temporal_phi.txt',
 'emb']

In [9]:
df.to_csv("../../data/cryptocurrencies_by_market_cap.csv")

In [10]:
#df.sort("MarketCap")

In [ ]:
# CRIPTO CURRENCIES
cryptocurrencies_dir = "/home/cesar/Desktop/Doctorado/Projects/BitCoin/Data/CryptoCurrenciesData/"
#os.listdir(cryptocurrencies_dir)

In [30]:
cryptocurrencies = {}
ticker = "BTC"
for ticker in df["Ticker"][0:10].values:
    try:
        CRYPTOCURRENCY = pd.read_csv(cryptocurrencies_dir+"cryptocurrencies_{0}.csv".format(ticker),parse_dates=True,index_col=0)
        cryptocurrencies[ticker] = CRYPTOCURRENCY["high"]
    except:
        pass

# PRICE AND VOLATILITY

In [39]:
        
    fig = plt.figure(figsize=(12, 6))
    gs = gridspec.GridSpec(3, 1, height_ratios=[7, 7, 1])

    ax0 = plt.subplot(gs[0])
    ax0.plot(time_support,excitations, "k-",label="excitations", color="#168EF7")
    #ax0.grid(True)
    ax0.set_ylabel(r'Excitations', fontsize=18)
    ax0.get_xaxis().set_visible(False)
    ax0.legend(bbox_to_anchor=(0., 1.02, 1., .102), loc=3, ncol=2, mode="expand", borderaxespad=0.)


    ax1 = plt.subplot(gs[1])
    ax1.plot(time_support,intensity, "k-",label="Intensities", color="#168EF7")
    #ax1.grid(True)
    ax1.set_ylabel(r'Intensities', fontsize=18)
    ax1.get_xaxis().set_visible(False)
    ax1.legend(bbox_to_anchor=(0., 1.02, 1., .102), loc=3, ncol=2, mode="expand", borderaxespad=0.)

    ax2 = plt.subplot(gs[2])
    ax2.vlines(filtration, ymin=0, ymax=1, color="#F88017",alpha=.9, label="Arrivals")

    plot_limit = (0, T)

    ax0.set_xlim(plot_limit)
    ax1.set_xlim(plot_limit)
    #ax1.get_yaxis().set_visible(False)
    ax1.get_xaxis().set_visible(False)
    ax2.set_xlim(plot_limit)
    #ax2.get_yaxis().set_visible(False)
    ax2.set_xlabel(r'Time ($t$)', fontsize=18)
    # fig.tight_layout()

    ax0.tick_params(axis='both', which='major', labelsize=14)
    ax1.tick_params(axis='both', which='minor', labelsize=14)
    ax2.tick_params(axis='both', which='minor', labelsize=14)
    if save_to_file is None:
        plt.show()
    else:
        plt.savefig(save_to_file)
    plt.close()

9

In [38]:
for ticker, crypto in cryptocurrencies.iteritems():
    crypto.plot()
    plt.close()

In [25]:
CRYPTOCURRENCY

             timestamp        open        high         low       close
date
2010-07-17  1279324800     0.04951     0.04951     0.04951     0.04951
2010-07-18  1279411200     0.04951     0.08585     0.05941     0.08584
2010-07-19  1279497600     0.08584     0.09307     0.07723     0.08080
2010-07-20  1279584000     0.08080     0.08181     0.07426     0.07474
2010-07-21  1279670400     0.07474     0.07921     0.06634     0.07921
2010-07-22  1279756800     0.07921     0.08181     0.05050     0.05050
2010-07-23  1279843200     0.05050     0.06767     0.05050     0.06262
2010-07-24  1279929600     0.06262     0.06161     0.05049     0.05454
2010-07-25  1280016000     0.05454     0.05941     0.05050     0.05050
2010-07-26  1280102400     0.05050     0.05600     0.05000     0.05600
2010-07-27  1280188800     0.05600     0.06050     0.05300     0.06000
2010-07-28  1280275200     0.06000     0.06200     0.05400     0.05890
2010-07-29  1280361600     0.05890     0.06990     0.05710     0.06990
2010-07-30  1280448000     0.06990     0.06980     0.05820     0.06270
2010-07-31  1280534400     0.06270     0.06889     0.05600     0.06785
2010-08-01  1280620800     0.06785     0.06500     0.06000     0.06110
2010-08-02  1280707200     0.06110     0.06330     0.06000     0.06000
2010-08-03  1280793600     0.06000     0.06500     0.05900     0.06000
2010-08-04  1280880000     0.06000     0.06231     0.05700     0.05700
2010-08-05  1280966400     0.05700     0.06100     0.05800     0.06100
2010-08-06  1281052800     0.06100     0.06240     0.06070     0.06230
2010-08-07  1281139200     0.06230     0.06220     0.05900     0.05900
2010-08-08  1281225600     0.05900     0.06100     0.05900     0.06090
2010-08-09  1281312000     0.06090     0.07350     0.05930     0.07100
2010-08-10  1281398400     0.07100     0.07090     0.06651     0.07000
2010-08-11  1281484800     0.07000     0.07541     0.06000     0.06700
2010-08-12  1281571200     0.06700     0.07000     0.06141     0.07000
2010-08-13  1281657600     0.07000     0.06800     0.06450     0.06450
2010-08-14  1281744000     0.06450     0.06950     0.06450     0.06700
2010-08-15  1281830400     0.06700     0.06700     0.06500     0.06529
...                ...         ...         ...         ...         ...
2017-08-20  1503187200  4150.45000  4182.29000  4034.40000  4066.60000
2017-08-21  1503273600  4066.60000  4097.25000  3966.93000  4005.10000
2017-08-22  1503360000  4005.10000  4142.68000  3612.21000  4089.70000
2017-08-23  1503446400  4089.70000  4255.62000  4070.49000  4141.09000
2017-08-24  1503532800  4141.09000  4364.11000  4111.71000  4318.35000
2017-08-25  1503619200  4318.35000  4461.71000  4292.63000  4364.41000
2017-08-26  1503705600  4364.41000  4379.28000  4263.28000  4352.30000
2017-08-27  1503792000  4352.30000  4408.18000  4321.12000  4345.75000
2017-08-28  1503878400  4345.75000  4403.13000  4195.23000  4390.31000
2017-08-29  1503964800  4390.31000  4647.83000  4350.22000  4597.31000
2017-08-30  1504051200  4597.31000  4644.06000  4491.79000  4583.02000
2017-08-31  1504137600  4583.02000  4765.07000  4580.13000  4735.11000
2017-09-01  1504224000  4735.11000  4925.23000  4690.17000  4921.85000
2017-09-02  1504310400  4921.85000  4976.52000  4448.64000  4573.80000
2017-09-03  1504396800  4573.80000  4719.78000  4397.74000  4612.92000
2017-09-04  1504483200  4612.92000  4621.01000  4098.58000  4267.45000
2017-09-05  1504569600  4267.45000  4496.67000  4004.62000  4409.08000
2017-09-06  1504656000  4409.08000  4660.04000  4401.53000  4618.71000
2017-09-07  1504742400  4618.71000  4690.55000  4493.20000  4635.60000
2017-09-08  1504828800  4635.60000  4699.59000  4130.88000  4326.45000
2017-09-09  1504915200  4326.45000  4402.15000  4185.33000  4335.13000
2017-09-10  1505001600  4335.13000  4338.08000  4032.15000  4245.89000
2017-09-11  1505088000  4245.89000  4364.42000  4134.62000  4217.90000
2017-09-12  1505174400  4217.90000  4387.76000  4074.97000  4158.92000
2017-09-13  1505260800  4158.92000  4174.58000  3752.01000  3870.29000
2017-09-14  1505347200  3870.29000  3930.69000  3218.98000  3243.08000
2017-09-15  1505433600  3243.08000  3824.43000  2979.88000  3713.76000
2017-09-16  1505520000  3713.76000  3893.67000  3551.83000  3698.92000
2017-09-17  1505606400  3698.92000  3796.56000  3485.83000  3689.61000
2017-09-18  1505692800  3689.61000  4042.75000  3689.00000  4061.77000

[2622 rows x 5 columns]

In [18]:
cryptocurrencies_dir = "/home/cesar/Desktop/Doctorado/Projects/BitCoin/Data/CryptoCurrenciesData/"

array([u'BTC', u'ETH', u'BCH', u'XRP', u'DASH', u'LTC', u'XEM', u'MIOTA',
       u'XMR', u'ETC'], dtype=object)

In [11]:
# cryptocurrencies

# Important Dates

In [11]:
IMPORTANT_DATES = {}

IMPORTANT_DATES["A"] = [datetime.datetime(2016,5,25),datetime.datetime(2016,5,30)]
IMPORTANT_DATES["B"] = [datetime.datetime(2016,6,10),datetime.datetime(2016,6,17)]
IMPORTANT_DATES["C"] = [datetime.datetime(2016,6,20),datetime.datetime(2016,6,23)]
IMPORTANT_DATES["D"] = [datetime.datetime(2016,7,1),datetime.datetime(2016,8,3)]
IMPORTANT_DATES["E"] = [datetime.datetime(2016,12,20),datetime.datetime(2016,12,24)]
IMPORTANT_DATES["F"] = [datetime.datetime(2017,1,1),datetime.datetime(2017,1,5)]
IMPORTANT_DATES["G"] = [datetime.datetime(2017,1,5),datetime.datetime(2017,1,12)]
IMPORTANT_DATES["H"] = [datetime.datetime(2017,5,25),datetime.datetime(2017,5,27)]
IMPORTANT_DATES["I"] = [datetime.datetime(2017,7,13),datetime.datetime(2017,7,16)]
IMPORTANT_DATES["J"] = [datetime.datetime(2017,7,16),datetime.datetime(2017,7,21)]
IMPORTANT_DATES["K"] = [datetime.datetime(2017,8,3),datetime.datetime(2017,8,14)]
IMPORTANT_DATES["China"] = [datetime.datetime(2017,9,12),datetime.datetime(2017,9,15)]

In [14]:
IMPORTANT_DATES = pd.DataFrame(IMPORTANT_DATES)

In [15]:
IMPORTANT_DATES.to_csv("../../data/important_dates.csv")